insert into "Joke" (id, text)
values (DEFAULT, 'Two JavaScript developers walked into the variable bar. Ouch!'),
       (DEFAULT, 'q. Why was the JavaScript developer sad? a. Because he didn''t Node how to Express himself'),
       (DEFAULT,
        'q. Why did Jason cover himself with bubble wrap? a. Because he wanted to make a cross-domain JSONP request'),
       (DEFAULT,
        'q. Why did the software company hire drama majors from Starbucks? a. Because they needed JavaScript experts!'),
       (DEFAULT,
        'q. Why did the CoffeeScript developer keep getting lost? a. Because he couldn''t find his source without a map'),
       (DEFAULT,
        'q. What do you call __proto__? a. Dunder proto q. Michael Scott was the regional manager where? a. __mifflin__'),
       (DEFAULT,
        'q. How did the doctor revive the developer? a. The dev wasn''t responsive so the doc picked him up by his bootstraps'),
       (DEFAULT, 'q. Why did the developer go broke? a. Because he used up all his cache'),
       (DEFAULT, 'q. How do you comfort a JavaScript bug? a. You console it'),
       (DEFAULT, 'When a JavaScript date has gone bad, "Don''t call me, I''ll callback you. I promise!"'),
       (DEFAULT,
        'Dev1 saw a strange JavaScript function & asked, "What is this?". Dev2 responded, "I don''t know. I would''ve called you, but I was in a bind"'),
       (DEFAULT, 'q. Why did the C# developer fall asleep? a. Because he didn''t like Java.'),
       (DEFAULT,
        'q. Why did the JavaScript boxer goto the chiropractor? a. Because his backbone was angular from a knockout and required attention'),
       (DEFAULT,
        'q. How did the web developer hurt Comic Sans feelings? a. Once he saw the font he quickly changed it to Open Sans and exclaimed "In your @font-face!"'),
       (DEFAULT,
        'q. Why do C# and Java developers keep breaking their keyboards a. Because they use a strongly typed language'),
       (DEFAULT, 'q. Why was Ember.js turning red? a. Because it was EMBERrassed for not remEMBERing its route home'),
       (DEFAULT,
        'q. Why did the jQuery developer never have financial problems? a. Because he was in $.noConflict() mode');
